### PR TITLE
Allow using local references

### PR DESCRIPTION
**Pull request by Aver1y**
This allows providing bibliography entries through other ways than cite2url.
This wasn't possible previously, because cite2url would throw an error if a
citation without an url was found. Also it completely overwrote the references
field so we couldn't use that. The former was addressed by providing an option
url2cite-allow-dangling-citations to disable the error and the latter by
concatenating with existing references instead of overwriting them.

This is useful for manually providing bibliography entries in cases where cite2url can't get the metadata.

### CODE REVIEW

**Comment by phiresky** [comment]
Awesome! I previously just added missing citations manually to the cache file, but this is a good alternative - and concatenating instead of completely replacing makes sense too.

One thing before I merge this: 

By doing `if(meta["url2cite-allow-dangling-citations"] === false) continue;`
you are making the default for that value true, right? So in a document that does not use other references, it would not throw an error if some citations are not defined. I think it should default to false (i.e. removing the `===false`), since that could be a mistake in other use cases - unless you have reasons to do it this way?

Also, could you run `yarn run prettier index.ts` on the changed file? I usually add a precommit hook for that via `husky`, but looks like I forgot in this project.

Let me know if you need anything else.

**Comment by Aver1y** [comment]
No, the default is `true`. If the option is not set it is undefined and so it is not `=== false`, i.e. it takes the `true` branch.

I ran prettier and adapted my changes to it's formatting, however there were some other places in the file it wanted to change too. You probably configured it locally in some way?

I also changed the casting of refs to use `as` instead of an if else with a dead branch.

**Comment by phiresky** [comment]
Ah, think I misread the code. But then, shouldn't it throw if `url2cite-allow-dangling-citations` is false instead of if it is true? I've changed it here: https://github.com/phiresky/pandoc-url2cite/commit/85b7bd20aa22043faea02bbfa1fcc39e177369e4#diff-ed009b6b86b017532ef0489c77de5100L171 . I think that's what you intended? lmk before i publish new npm version.

The configuration of prettier is (should be) read from `package.json` (prettier: ...) because of cosmiconfig. But can be that since the precommit hook was missing I also committed unformatted code.

I've updated dependencies, changed prettier config to my preferred one, and changed the dependency of pandoc-filter back to upstream after the https://github.com/mvhenderson/pandoc-filter-node/pull/10 merge.

**Comment by Aver1y** [comment]
Ah, yes. That's what I intended.

**Comment by phiresky** [comment]
Great. Published pandoc-url2cite@0.6.4

**Pull request merged**
